title: Yulei Shen's CNS learning note
baseline: GOOD GOOD STUDY DAY DAY UP
description: Learning to be a researcher. Also, writing some dairies here.
baseurl: /
canonicalurl: true
keywords: [Cognitive Neuroscience]
author: Yulei Shen
date:
  format: j F Y
  timezone: Asia/Japan
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true # Content to the bottom of the sidebar
  theme: '' # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false # Reverse layout
